name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: uniladder_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/uniladder_test
      SECRET_KEY_BASE: 7a8e8d4d6b2b2e8a0b7b9f4c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f60718293aa4b5c6d7e8f90123456789abcdef0123456789abcdef0123456789abcdef

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
          bundler-cache: true

      - name: Prepare database
        run: bin/rails db:prepare

      - name: RuboCop
        run: bin/rubocop

      - name: Run tests
        run: bin/rails test -d
